version: "3"

services:
    db:
        build:
            context: .
            dockerfile: Dockerfile
    api:
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        expose:
            - 3000
    web:
        build:
            context: client
            dockerfile: Dockerfile
        ports:
            - "80:80"